# Generated by Django 6.0.3 on 2026-03-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(blank=True, max_length=500)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('polygon_coordinates', models.JSONField()),
                ('rooftop_area', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('annual_potential', models.FloatField(blank=True, null=True)),
                ('recommended_tank_size', models.CharField(blank=True, max_length=100)),
                ('recharge_feasibility', models.CharField(blank=True, max_length=100)),
                ('structure_type', models.CharField(blank=True, max_length=150)),
                ('rainfall_estimate', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
