# Generated by Django 6.0.3 on 2026-03-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='pdf_report',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
